import React from 'react';

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';

export default function ClassDiagram (props) {
    return (
        <Container maxWidth="lg">
          <Box>
            <pre>{data.join('\n')}</pre>
          </Box>
        </Container>
    );
}

const data = [
    '<<Model Class>>',
    '                                         +-------------+',
    '                                         | GraphQLNode |',
    '                                         |=============|',
    '                                         |- _core      |',
    '                                         |- _sogh      |',
    '                                         |-------------|',
    '                                         |+ core       |',
    '                                         |+ sogh       |',
    '                                         |+ id         |',
    '                                         |+ path       |',
    '                                         |+ createdAt  |      ? Card',
    '                                         |+ updatedAt  |      ? Column ? Relationship',
    '                                         +-------------+',
    '                                               ^',
    '                                               |',
    '     +------------------------+----------------+------------------+-------------+------------+---------+',
    '     |                        |                |                  |             |            |         |',
    '+------------------+  +--------------+  +--------------+    +------------+  +--------+  +----------+   |',
    '| Repository       |  | Label        |  | Milestone    |    | User       |  | Viewer |  | Assignee |   |',
    '|==================|  |==============|  |==============|    |============|  |========|  |==========|   |',
    '|------------------|  |--------------|  |--------------|    |------------|  |--------|  |----------|   |',
    '|+ url             |  |+ url         |  |+ url         |    |+ url       |  |+ url   |  |+ url     |   |',
    '|+ name            |  |+ color       |  |+ title       |    |+ login     |  |+ login |  |+ login   |   |',
    '|+ description     |  |+ name        |  |+ number      |    |+ name      |  |+ name  |  |+ name    |   |',
    '|+ descriptionHTML |  |+ description |  |+ state       |    |+ email     |  +--------+  |+ email   |   |',
    '|+ owner           |  |+ fontColor   |  |+ description |    |+ company   |              |+ company |   |',
    '|+ pushedAt        |  +--------------+  |+ closedAt    |    |+ avatarUrl |              +----------+   |',
    '+------------------+                    |+ dueOn       |    +------------+                             |',
    '                                        +--------------+                                               |',
    '                                                                                                       |',
    '                     +---------------------------------------------------------------------------------+',
    '                     |                                                                    |',
    '       +-------------+---------------+                                     +--------------+-------------+',
    '       |                             |                                     |                            |',
    '+--------------+    +-----------------------------------+      +-----------------------+     +----------------------+',
    '| IssueComment |    | Issue                             |      | ProjectNext           |     | ProjectNextItem      |',
    '|==============|    |===================================|      |=======================|     |======================|',
    '|--------------|    |- _owner                           |      |- _priority            |     |----------------------|',
    '|+ body        |    |- _date_next_action                |      |- _owner               |     |+ title               |',
    '|+ bodyHTML    |    |- _due_date                        |      |- _type                |     |+ isArchived          |',
    '|+ url         |    |- _points                          |      |- _release             |     |+ type                |',
    '|+ publishedAt |    |-----------------------------------|      |- _plan                |     |+ content             |',
    '|+ author      |    |+ url                              |      |- _result              |     |+ fieldValues         |',
    '+--------------+    |+ number                           |      |-----------------------|     |- getFieldValueByName |',
    '                    |+ title                            |      |+ url                  |     |+ status              |',
    '                    |+ closedAt                         |      |- initReadmeAttributes |     |+ dueDate             |',
    '                    |+ milestone                        |      |- initRegexs           |     |+ nextActionDate      |',
    '                    |+ projectCards                     |      |- parseReadme          |     |+ plans               |',
    '                    |+ assignees                        |      |+ number               |     |+ resutls             |',
    '                    |+ labels                           |      |+ title                |     |+ before              |',
    '                    |+ owner                            |      |+ fields               |     |+ after               |',
    '                    |+ points                           |      |+ shortDescription     |     +----------------------+',
    '                    |+ pointPlansTotal                  |      |+ readme               |',
    '                    |+ pointResultTotal                 |      |+ public               |',
    '                    |+ body                             |      |+ owner                |',
    '                    |+ bodyHTML                         |      |+ creator              |',
    '                    |+ dueDate                          |      |                       |',
    '                    |+ nextActionDate                   |      |+ priority             |',
    '                    |- getPointResultsFromBody          |      |+ owner                |',
    '                    |- getPointPlansFromBody            |      |+ type                 |',
    '                    |- getPointFromBody                 |      |+ release              |',
    '                    |- getDueDateFromBody               |      |+ plan                 |',
    '                    |- getNextActionFromBody            |      |+ result               |',
    '                    |- getOwnerFromBody                 |      +-----------------------+',
    '                    |- addAnotetionValue                |',
    '                    |- addAnotetionValueNew             |',
    '                    |+ makeIssueData                    |',
    '                    |- issueData2requestDataDescription |',
    '                    |- issueData2requestData            |',
    '                    |? getColumnFirst                   |',
    '                    |? getFirstColumnProject            |',
    '                    |? getFirstColumnProjectID          |',
    '                    |? milestoneId                      |',
    '                    |? projects                         |',
    '                    |? projectIds                       |',
    '                    +-----------------------------------+',
    '',
    '',
    '<<Simple data class>>',
    '',
    '+--------------+',
    '| Term         |',
    '|==============|',
    '|+ constructor |',
    '|--------------|',
    '|+ start       |',
    '|+ end         |',
    '+--------------+',
];
